apiVersion: v1
kind: Secret
metadata:
  name: fraudshield-secrets
  namespace: fraudshield
type: Opaque
stringData:
  transaction-db-url: postgresql://fraudshield:fraudshield123@postgres:5432/fraudshield_db
  fraud-db-url: postgresql://fraudshield:fraudshield123@postgres:5432/fraudshield_db
  redis-url: redis://redis:6379/0
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: fraudshield-config
  namespace: fraudshield
data:
  kafka-broker: fraudshield-kafka-kafka-bootstrap.kafka.svc.cluster.local:9092
  topic-transaction-initiated: transactions.initiated
  topic-fraud-verdict: fraud.verdict
