apiVersion: apps/v1
kind: Deployment
metadata:
  name: transaction-service
  namespace: fraudshield
  labels:
    app: transaction-service
    version: "1.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: transaction-service
  template:
    metadata:
      labels:
        app: transaction-service
    spec:
      containers:
        - name: transaction-service
          image: fraudshield-transaction:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: fraudshield-secrets
                  key: transaction-db-url
            - name: KAFKA_BROKER
              valueFrom:
                configMapKeyRef:
                  name: fraudshield-config
                  key: kafka-broker
            - name: TOPIC_TRANSACTION_INITIATED
              valueFrom:
                configMapKeyRef:
                  name: fraudshield-config
                  key: topic-transaction-initiated
            - name: TOPIC_FRAUD_VERDICT
              valueFrom:
                configMapKeyRef:
                  name: fraudshield-config
                  key: topic-fraud-verdict
          readinessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 20
            periodSeconds: 10
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"
